---
repository:
  name: kleister-secrets
  description: "Kleister: Secrets"
  homepage: https://kleister.eu

  private: false
  has_issues: false
  has_wiki: false
  has_downloads: false

  default_branch: master

  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true

  allow_update_branch: true
  allow_auto_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

...
